# c.f. https://github.com/commercialhaskell/stack/wiki/Travis
sudo: false

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - mkdir -p ~/.local/lib
  - export PATH=~/.local/bin:$PATH
  - export LD_LIBRARY_PATH=~/.local/lib:$LD_LIBRARY_PATH
  - ./scripts/install-z3.sh
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/7.10.3/bin:$PATH

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.3
    - libgmp-dev

script:
  - stack --no-terminal --skip-ghc-check build --ghc-options=-ferror-spans
  - stack exec formura-parser examples/diffusion.f31
  - stack exec formura-gen examples/diffusion.f31
  - stack test
  - echo "done test"
